const constants = {
	UPDATE_EMPLOYEE:"UPDATE_EMPLOYEE",
	SET_EMPLOYEES: "SET_EMPLOYEES",
	ADD_EMPLOYEES:"ADD_EMPLOYEES",
	REMOVE_EMPLOYEES: "REMOVE_EMPLOYEES",
	
	UPDATE_CAMPAIGN: "UPDATE_CAMPAIGN",
	SET_CAMPAIGNS: "SET_CAMPAIGNS",
	ADD_CAMPAIGNS: "ADD_CAMPAIGNS",
	REMOVE_CAMPAIGNS: "REMOVE_CAMPAIGNS",
	SELECT_CAMPAIGN: "SELECT_CAMPAIGN",
	

	UPDATE_SEARCH_TEXT:"UPDATE_SEARCH_TEXT",
}
export default constants